version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pdl-fullmakt
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432


  pdl-fullmakt:
    image: navikt/pdl-fullmakt:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "POSTGRES_URL=jdbc:postgresql://postgres:5432/pdl-fullmakt"
    ports:
      - 8081:8080
    volumes:
      - ./travis/pdlfullmakt-private-key.pem:/etc/secret/pdl-fullmakt

volumes:
  postgres: