apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdlfullmakt
  namespace: default
  labels:
    team: pdlfullmakt
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - "https://pdl-fullmakt.prod-fss.nais.io"
    - "https://pdl-fullmakt.nav.no"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  liveness:
    path: internal/isAlive
    initialDelay: 60
  readiness:
    path: internal/isReady
    initialDelay: 60
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
    requests:
      memory: 528Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: internal/metrics
