
CREATE SEQUENCE IF NOT EXISTS SEQ_FULLMAKT;

CREATE TABLE IF NOT EXISTS FULLMAKT
(
    FULLMAKT_ID INTEGER DEFAULT NEXTVAL('SEQ_FULLMAKT') PRIMARY KEY,
    REGISTRERT TIMESTAMP WITH TIME ZONE NOT NULL,
    REGISTRERT_AV VARCHAR(20)  NOT NULL,
    ENDRET TIMESTAMP WITH TIME ZONE,
    ENDRET_AV VARCHAR(20) ,
    OPPHOERT BOOLEAN,
    FULLMAKTSGIVER VARCHAR(20)  NOT NULL,
    FULLMEKTIG VARCHAR(20)  NOT NULL,
    OMRAADE VARCHAR(100) ,
    GYLDIG_FRA_OG_MED DATE,
    GYLDIG_TIL_OG_MED DATE,
    UNIQUE (FULLMAKTSGIVER, FULLMEKTIG, OMRAADE, GYLDIG_FRA_OG_MED )
);

CREATE TABLE IF NOT EXISTS FULLMAKT_ENDRINGSLOGG
(
    FULLMAKT_ID INTEGER NOT NULL,
    REGISTRERT TIMESTAMP WITH TIME ZONE NOT NULL,
    REGISTRERT_AV VARCHAR(20)  NOT NULL,
    ENDRET TIMESTAMP WITH TIME ZONE,
    ENDRET_AV VARCHAR(20) ,
    OPPHOERT BOOLEAN,
    FULLMAKTSGIVER VARCHAR(20)  NOT NULL,
    FULLMEKTIG VARCHAR(20)  NOT NULL,
    OMRAADE VARCHAR(100) ,
    GYLDIG_FRA_OG_MED DATE,
    GYLDIG_TIL_OG_MED DATE,
    HISTORIE_DATO TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

