
CREATE TABLE IF NOT EXISTS FULLMAKT
(
    LIST_NAME          VARCHAR(100) NOT NULL,
    CODE               VARCHAR(100) NOT NULL,
    DESCRIPTION        VARCHAR(500) NOT NULL,
    CREATED_BY         VARCHAR(200) NOT NULL,
    CREATED_DATE       TIMESTAMP    NOT NULL,
    LAST_MODIFIED_BY   VARCHAR(200),
    LAST_MODIFIED_DATE TIMESTAMP,
    UNIQUE (LIST_NAME, CODE)
);

